version: 0.2
phases:
  install:
  	runtime-versions:
      java: openjdk8
   build:
    commands:
      - echo Build started on `date`
      - mvn package 
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation package --template-file samtemplate.yaml --s3-bucket cd-sample-sam --output-template-file outputSamTemplate.yaml
artifacts:
  
  files:
  	- target/sample-1.0.0.jar
    - samtemplate.yaml
    - outputSamTemplate.yaml
